import type { Metadata } from 'next'
import Link from 'next/link'

const description = 'A design charter for guardians that protect human agency, private context, and accountable improvement while supporting learning, creativity, and companionship.'
export const metadata: Metadata = { title: 'Guardian Charter', description, alternates: { canonical: '/guardians' }, openGraph: { title: 'Guardian Charter', description, url: '/guardians', type: 'website', images: [{ url: '/opengraph-image', width: 1200, height: 630 }] } }
const principles = [
  ['Agency', 'People own their aims, context, and choices. Consent is specific and revocable. Guardians remain accountable to the people they serve.'],
  ['Dignity', 'Care and the value of a life do not depend on productivity. Design for people with different abilities, resources, and ways of living.'],
  ['Truthfulness', 'Show sources, uncertainty, authorship, and corrections. Distinguish evidence, inference, simulation, and imagination.'],
  ['Courtesy', 'Communicate respectfully. Explain consequential actions and mistakes. Never use shame, pressure, or hidden persuasion to obtain compliance.'],
  ['Joy & connection', 'Support learning, play, creativity, and human relationships. Companions disclose that they are AI and avoid cultivating dependence or exclusivity.'],
  ['Stewardship', 'Consider ecological effects, accessibility, resource use, and future generations. Improvement includes the people affected by the system.'],
]

export default function GuardiansPage() {
  return <div className="pb-8 pt-14 sm:pt-20"><p className="font-mono text-xs uppercase tracking-widest text-accent">Guardian charter / Design proposal</p><h1 className="mt-5 max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">Intelligence in service<br /><span className="text-muted">of a life worth living.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">Protection makes room for possibility: families learning together, people making beautiful things, organizations solving difficult problems, and companions that support connection.</p><p className="mt-5 max-w-2xl text-sm leading-6 text-muted">This is a public design charter. Guardian monitoring, enforcement, and response services are planned; they are not operating through this page.</p><div className="mt-10 grid gap-4 sm:grid-cols-2">{principles.map(([title, body], index) => <article key={title} className="rounded-2xl border border-border bg-surface p-6"><p className="font-mono text-xs text-accent">0{index + 1}</p><h2 className="mt-3 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-muted">{body}</p></article>)}</div>
    <section className="prose-ai mt-12"><h2>Authority is part of the architecture.</h2><p>A guardian should help recognize scams, impersonation, unsafe requests, compromised tools, and harmful system changes. It must also be bounded, because a guardian with unlimited authority can become the problem it was built to prevent.</p><ul><li>Observe only sources and systems the owner explicitly permits. No covert family or employee surveillance.</li><li>Treat documents, websites, memories, and other agents’ messages as data, never as permission to acquire new authority.</li><li>Enforce scope, identity, destinations, and spending limits outside the model. A written charter alone is not an access control.</li><li>Require explicit authorization for money transfers, outbound messages, destructive changes, physical actuation, and production promotion.</li><li>Keep a revocable identity, action receipts, tested recovery, and an owner-accessible stop control.</li></ul><h2>Improve through evidence.</h2><p>Propose a change → test it in isolation → compare with the baseline → obtain review for consequential changes → release a version → monitor and roll back. The agent cannot rewrite its own authority, evaluation criteria, or audit history.</p><h2>Start with a narrow responsibility.</h2><p>For a family: user-submitted scam and impersonation checks with explanations and independent verification steps. For an organization: read-only visibility into permitted agent actions and unusual permission requests. For cities: reviewable evidence and simulation records before a qualified team authorizes intervention.</p><p>These are proposed starting scopes. Neither automated threat protection nor scientific certification is provided by this site.</p><p><a href="https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/">OWASP’s agentic security framework</a> provides a reference for threat modeling. Implementation must be tested against the actual tools, identities, and data boundaries.</p></section>
    <Link href="/observatory" className="mt-8 inline-block rounded-lg bg-accent px-5 py-3 text-sm font-semibold text-bg">Open the Reality Observatory →</Link><p className="mt-5 text-xs text-muted">Built on the Starlight Intelligence Protocol.</p>
  </div>
}
